### ISSUE TITLE
Config file to add modded elytras?

### ISSUE THREAD

**Issue by yojakeo** [Saphjyr/ElytraChestplateSwapper#1]
First off I'd like to say I love your mod! It's such a small thing but it's super neat.

My only issue I'm running into is with non-vanilla elytra (Netherite elytra, custom elytra, etc) it either doesn't register it at all or if it has an armor value, assumes it's a chestplate.

Perhaps something as simple as a config file that has item tags that the mod will accept as elytra? You could get fancy if you wanna and build it into the modlist config screen.

Either way. Thanks for this neat little mod!

**Comment by Saphjyr** [comment]
Thanks for the feedback!

Do you have a link to a project that do not work with this mod ? The only netherite elytra I found was a forge mod.

As it is, this mod should work with custom items that are built from the ElytraItem. But maybe there are some projects that do it in a different way.
