### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by JasonHorkles** [Saphjyr/ElytraChestplateSwapper#10]
MC won't launch due to this not supporting 1.20.1 - I imagine all that's needed is a version bump but I'm more than happy to test if anything else needs done

**Comment by david-0609** [comment]
I have compiled it to support 1.20, this is unofficial but usable for now
https://filebin.net/3pkwps3p05kfkdij/elytra-chestplate-swapper-1.3.0-MC1.20.jar

**Comment by david-0609** [comment]
I opened a pull request with the update, hopefully the author would merge it

**Comment by Saphjyr** [comment]
I'll publish the updated version of the jar in a few hours, I don't have access to my latency test setup rn.

Thanks for the pull request btw, I don't know why I could not build my version.
